# Generated by Django 5.0.6 on 2024-06-12 15:54

from django.db import migrations


def fill_roles(apps, schema_editor):
    Role = apps.get_model('api', 'Role')

    Role.objects.create(id=1, name='Клиент')
    Role.objects.create(id=2, name='Курьер')
    Role.objects.create(id=3, name='Официант')
    Role.objects.create(id=4, name='Админ')
    Role.objects.create(id=5, name='Работник зала')
    Role.objects.create(id=6, name='Работник кухни')


def clear_roles(apps, schema_editor):
    Role = apps.get_model('api', 'Role')

    Role.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_user_shifts'),
    ]

    operations = [
        migrations.RunPython(fill_roles, clear_roles)
    ]
