# Generated by Django 5.0.6 on 2024-06-12 16:05

from django.db import migrations


def add_admin(apps, schema_editor):
    User = apps.get_model('api', 'User')

    User.objects.create_superuser(
        username='admin',
        password='admin',
        first_name='Клейн',
        last_name='Моретти',
        phone_number='89777777777',
        role_id=4
    )


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20240612_1954'),
    ]

    operations = [
        migrations.RunPython(add_admin)
    ]
